unknown sidechat "Anyone this net, I need help!";
playSoundUI ["ax_radioclick"];
sleep 4;
pl1 sidechat "Requesting callsign. Over.";
playSoundUI ["ax_radioclick"];
sleep 4;
unknown sidechat "This is Myrmidon! I'm at Outpost Cresate!";
playSoundUI ["ax_radioclick"];
sleep 4;
myrmidon sidechat "The Americans wrecked this place, but I was able to hide my APC!";
playSoundUI ["ax_radioclick"];
sleep 7;
myrmidon sidechat "But, my crew are kia! I'm the only one left. Over...";
playSoundUI ["ax_radioclick"];
sleep 6;
pl1 sidechat "Bit far from us. We'll see if we can extract you. Over.";
playSoundUI ["ax_radioclick"];
sleep 6;
myrmidon sidechat "Thanks... Out.";
playSoundUI ["ax_radioclick"];