// Player
removeAllWeapons player;
removeAllItems player;
removeAllAssignedItems player;
removeUniform player;
removeVest player;
removeBackpack player;
removeHeadgear player;
removeGoggles player;
player addWeapon "rhs_weap_m4a1_d";
player addPrimaryWeaponItem "rhsusf_acc_eotech_552_d";
player addPrimaryWeaponItem "rhs_mag_30Rnd_556x45_M855A1_EPM";
player forceAddUniform "rhs_uniform_acu_oefcp";
player addVest "rhsusf_iotv_ocp_Rifleman";
player addBackpack "rhsusf_assault_eagleaiii_ocp";
player addItemToUniform "FirstAidKit";
player addItemToUniform "FirstAidKit";
for "_i" from 1 to 6 do {player addItemToVest "rhs_mag_30Rnd_556x45_M855A1_EPM";};
for "_i" from 1 to 2 do {player addItemToVest "rhs_mag_m67";};
player addItemToBackpack "rhs_weap_m24sws_d";
player addItemToBackpack "rhsusf_acc_m24_muzzlehider_d";
player addItemToBackpack "rhsusf_acc_harris_swivel";
player addItemToBackpack "rhsusf_acc_LEUPOLDMK4_d";
for "_i" from 1 to 3 do {player addItemToBackpack "rhsusf_5Rnd_762x51_m993_Mag";};
player addHeadgear "rhsusf_ach_helmet_ocp";
player linkItem "ItemMap";
player linkItem "ItemCompass";
player linkItem "ItemWatch";
player linkItem "ItemRadio";
[player,"GreekHead_A3_05","male09eng"] call BIS_fnc_setIdentity;

// Backpack man
removeAllWeapons p_1;
removeAllItems p_1;
removeAllAssignedItems p_1;
removeUniform p_1;
removeVest p_1;
removeBackpack p_1;
removeHeadgear p_1;
removeGoggles p_1;
p_1 addWeapon "rhs_weap_m4a1_d";
p_1 addPrimaryWeaponItem "rhsusf_acc_eotech_552_d";
p_1 addPrimaryWeaponItem "rhs_mag_30Rnd_556x45_M855A1_EPM";
p_1 forceAddUniform "rhs_uniform_acu_oefcp";
p_1 addVest "rhsusf_iotv_ocp_Rifleman";
p_1 addItemToUniform "FirstAidKit";
p_1 addItemToUniform "FirstAidKit";
p_1 addItemToUniform "FirstAidKit";
p_1 addBackpack "UK3CB_CSAT_F_O_B_ENG_UCP";
for "_i" from 1 to 6 do {p_1 addItemToVest "rhs_mag_30Rnd_556x45_M855A1_EPM";};
for "_i" from 1 to 25 do {p_1 addItemToBackpack "rhs_mag_30Rnd_556x45_M855A1_EPM";};
for "_i" from 1 to 10 do {p_1 addItemToBackpack "FirstAidKit";};
for "_i" from 1 to 2 do {p_1 addItemToVest "rhs_mag_m67";};
p_1 addHeadgear "rhsusf_ach_helmet_ocp";
p_1 linkItem "ItemMap";
p_1 linkItem "ItemCompass";
p_1 linkItem "ItemWatch";
p_1 linkItem "ItemRadio";
[p_1,"GreekHead_A3_06","male12eng"] call BIS_fnc_setIdentity;

{
	removeAllWeapons _x;
	removeAllItems _x;
	removeAllAssignedItems _x;
	removeUniform _x;
	removeVest _x;
	removeBackpack _x;
	removeHeadgear _x;
	removeGoggles _x;
	_x addWeapon "rhs_weap_m4a1_d";
	_x addPrimaryWeaponItem "rhsusf_acc_eotech_552_d";
	_x addPrimaryWeaponItem "rhs_mag_30Rnd_556x45_M855A1_EPM";
	_x forceAddUniform "rhs_uniform_acu_oefcp";
	_x addVest "rhsusf_iotv_ocp_Rifleman";
	_x addItemToUniform "FirstAidKit";
	_x addItemToUniform "FirstAidKit";
	for "_i" from 1 to 6 do {_x addItemToVest "rhs_mag_30Rnd_556x45_M855A1_EPM";};
	for "_i" from 1 to 2 do {_x addItemToVest "rhs_mag_m67";};
	_x addHeadgear "rhsusf_ach_helmet_ocp";
	_x linkItem "ItemMap";
	_x linkItem "ItemCompass";
	_x linkItem "ItemWatch";
	_x linkItem "ItemRadio";
} forEach [p_1, p_2];
[p_2,"WhiteHead_04","male12eng"] call BIS_fnc_setIdentity;
[p_3,"WhiteHead_04","male05eng"] call BIS_fnc_setIdentity;
